name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Use latest v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # v3 is stable

      - name: Log in to Docker Hub
        uses: docker/login-action@v3         # use v3 (more stable + secure)
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: devdot021/product-catalog-service:v1.0.0
